defaultMarkdownHandler = "goldmark"

[goldmark]

  [goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

  [goldmark.parser]
    autoHeadingID = true
    wrapStandAloneImageWithinParagraph = false

    [goldmark.parser.attribute]
      block = true
      title = true

  [goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false

[highlight]
  codeFences = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = false
  noClasses = true
  style = "monokai"
  tabWidth = 4

[tableOfContents]
  endLevel = 6
  ordered = false
  startLevel = 2
