[[main]]
name = "About"
url = "about"
weight = 10
title = "Meet the Author"

[[main]]
name = "Blog"
url = "blog"
weight = 20
title = "Explore my Blog"

[[main]]
name = "Contact"
url = "#"
weight = 20
title = "Get in touch"
