name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: NPM Install
        run: npm install

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.121.1"
          extended: true

      - name: Build for test
        run: hugo --source testSuite --baseUrl '/' --cleanDestinationDir --enableGitInfo --gc
        if: ${{ false }}

      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml
        if: ${{ false }}

      - name: Build
        run: hugo --source testSuite --minify --cleanDestinationDir --enableGitInfo --gc --printPathWarnings --templateMetrics

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.APP_TOKEN }}
          external_repository: joelbladt/joelbladt.github.io
          publish_dir: ./docs
          #   keep_files: true
          user_name: joelbladt
          user_email: joel@bladt.de
          publish_branch: gh-pages
          #   cname: example.com
